### ISSUE TITLE
سلام ممنون از کار خوبتون

### ISSUE THREAD

**Issue by majid1221** [majidh1/iranianNationalCode#1]
سلام بسیار ممنونم از کار خوبتون همیشه ازش استفاده میکنم
لطفا راهنمایی کنید که چطور از کد مربوطه استفاده کنیم؟ کد صحت کد ملی رو پیدا نکردم

**Comment by majidh1** [comment]
سلام ممنون از شما کد مربوطه در آدرس زیر موجود است
/src/iranianNationalCodeValidator.js

از بخش code وارد src شوید و فایل iranianNationalCodeValidator.js را مشاهده کنید
